# Generated by Django 4.2.5 on 2023-09-30 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measurements', '0002_remove_measurement_sensor_id_measurement_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayedSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurements.sensor')),
            ],
        ),
    ]
